[workspace]
members = [
    "contracts/packages/interfaces",
    "contracts/packages/budokan",
    "contracts/packages/rewards",
    "contracts/packages/viewer",
]

[workspace.package]
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.16.0"

[workspace.dependencies]
starknet = "2.16.1"
cairo_test = "2.16.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.58.1" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
game_components_embeddable_game_standard = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
game_components_metagame = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
game_components_utilities = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
game_components_interfaces = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
game_components_test_common = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
game_components_testing = { git = "https://github.com/Provable-Games/game-components.git", branch = "main" }
metagame_extensions_interfaces = { git = "https://github.com/Provable-Games/metagame_extensions.git", tag = "v0.1.4" }

[scripts]
test = "snforge test"

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true
inlining-strategy = "avoid"

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]

[tool.snforge]
# Fork configurations for testing
[[tool.snforge.fork]]
name = "sepolia"
url = "https://starknet-sepolia.public.blastapi.io"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "mainnet"
url = "https://starknet-mainnet.public.blastapi.io"
block_id.tag = "latest"
