[package]
name = "budokan_viewer"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
budokan_interfaces = { path = "../interfaces" }
game_components_interfaces.workspace = true
openzeppelin_access.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_upgrades.workspace = true

[dev-dependencies]
snforge_std.workspace = true
budokan = { path = "../budokan" }
budokan_rewards = { path = "../rewards" }
game_components_embeddable_game_standard.workspace = true
game_components_test_common.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "budokan::budokan::Budokan",
    "budokan_rewards::budokan_rewards::BudokanRewards",
    "game_components_test_common::mocks::minigame_mock::minigame_mock",
    "game_components_test_common::examples::minigame_registry_contract::MinigameRegistryContract",
    "game_components_test_common::examples::full_token_contract::FullTokenContract",
    "budokan::mocks::erc20_mock::erc20_mock",
]
