[package]
name = "budokan"
version.workspace = true
edition.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "game_components_test_common::mocks::minigame_mock::minigame_mock",
    "game_components_test_common::mocks::metagame_mock::metagame_mock",
    "game_components_test_common::examples::full_token_contract::FullTokenContract",
    "game_components_test_common::examples::minigame_registry_contract::MinigameRegistryContract",
]

[cairo]
sierra-replace-ids = true

[dependencies]
starknet.workspace = true
openzeppelin_access.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_token.workspace = true
openzeppelin_interfaces.workspace = true
openzeppelin_upgrades.workspace = true
game_components_embeddable_game_standard.workspace = true
game_components_metagame.workspace = true
game_components_utilities.workspace = true
game_components_interfaces.workspace = true
game_components_test_common.workspace = true
metagame_extensions_interfaces.workspace = true
budokan_interfaces = { path = "../interfaces" }

[dev-dependencies]
cairo_test = "2.16.1"
snforge_std.workspace = true

[features]
default = []
